feat: implement SQL rejection mechanism with configurable regex patterns (#453)
* feat: implement file watcher with callback functionality

* feat: implement SQL rejection mechanism with configurable regex patterns

* feat: add configurable regex for SQL rejection and update config handling

* feat: refactor config handling

* feat: enhance tests for SQL rejection regex and logging configuration

* test: add end-to-end tests and coverage reporting for taosAdapter

* build: update CI configuration for testing and adjust OS matrix

* fix: correct connection reference in pool tests

* feat: enhance SQL rejection logic with additional regex patterns and trim whitespace from queries

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -124,6 +124,7 @@ jobs:
           (github.event_name == 'pull_request' && steps.cache-server-pr.outputs.cache-hit != 'true') ||
           (github.event_name == 'push' && steps.cache-server-push.outputs.cache-hit != 'true')
         run: |
+          tree ./TDengine/debug/build
           mkdir -p ./release
           cp ./TDengine/debug/build/bin/taos ./release/
           cp ./TDengine/debug/build/bin/taosd ./release/
@@ -266,7 +267,9 @@ jobs:
 
       - name: test
         id: test
-        run: sudo go test -coverpkg=./... -v --count=1 -coverprofile=coverage.txt -covermode=atomic ./...
+        env:
+          GO_TEST_DISABLE_DISPLAY_LOG: "true"
+        run: go test -coverpkg=./... -v --count=1 -coverprofile=coverage.txt -covermode=atomic ./...
 
       - name: Upload coverage to Codecov
         if: matrix.os == 'ubuntu-latest'
@@ -350,7 +353,8 @@ jobs:
     name: Build-asan${{ matrix.os }}
     strategy:
       matrix:
-        os: [ 'ubuntu-latest' , 'ubuntu-24.04-arm' ]
+        #       asan runs failed on 24.04, see: https://github.com/cockroachdb/pebble/issues/5342
+        os: [ 'ubuntu-22.04' , 'ubuntu-22.04-arm' ]
     outputs:
       commit_id: ${{ steps.get_commit_id.outputs.commit_id }}
     steps:
@@ -468,7 +472,8 @@ jobs:
     strategy:
       matrix:
         go: [ 'stable' ]
-        os: [ 'ubuntu-latest' , 'ubuntu-24.04-arm' ]
+        #       asan runs failed on 24.04, see: https://github.com/cockroachdb/pebble/issues/5342
+        os: [ 'ubuntu-22.04' , 'ubuntu-22.04-arm' ]
     name: test taosAdapter with asan ${{ matrix.os }}-${{ matrix.go }}
     steps:
       - name: get cache server by pr
@@ -525,7 +530,9 @@ jobs:
 
       - name: test
         id: test
-        run: sudo go test -v --count=1 -asan ./...
+        env:
+          GO_TEST_DISABLE_DISPLAY_LOG: "true"
+        run: go test -v --count=1 -asan ./...
 
   govulncheck:
     name: govulncheck
@@ -581,3 +588,89 @@ jobs:
 
       - name: Run vulnerability scan
         run: govulncheck ./...
+
+  test_e2e:
+    name: test_e2e
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ 'ubuntu-latest' , 'ubuntu-24.04-arm' ]
+    needs: build
+    steps:
+      - name: get cache server by pr
+        if: github.event_name == 'pull_request'
+        id: get-cache-server-pr
+        uses: actions/cache@v4
+        with:
+          path: server.tar.gz
+          key: ${{ matrix.os }}-build-${{ github.base_ref }}-${{ needs.build.outputs.commit_id }}
+          restore-keys: |
+            ${{ matrix.os }}-build-${{ github.base_ref }}-
+
+      - name: get cache server by push
+        if: github.event_name == 'push'
+        id: get-cache-server-push
+        uses: actions/cache@v4
+        with:
+          path: server.tar.gz
+          key: ${{ matrix.os }}-build-${{ github.ref_name }}-${{ needs.build.outputs.commit_id }}
+          restore-keys: |
+            ${{ matrix.os }}-build-${{ github.ref_name }}-
+
+      - name: get cache server manually
+        if: github.event_name == 'workflow_dispatch'
+        id: get-cache-server-manually
+        uses: actions/cache@v4
+        with:
+          path: server.tar.gz
+          key: ${{ matrix.os }}-build-${{ inputs.tbBranch }}-${{ needs.build.outputs.commit_id }}
+          restore-keys: |
+            ${{ matrix.os }}-build-${{ inputs.tbBranch }}-
+
+      - name: install
+        run: |
+          tar -zxvf server.tar.gz
+          cd release && sudo sh install.sh
+
+      - name: checkout
+        uses: actions/checkout@v4
+
+      - name: copy taos cfg
+        run: |
+          sudo mkdir -p /etc/taos
+          sudo cp ./.github/workflows/taos.cfg /etc/taos/taos.cfg
+
+      - uses: actions/setup-go@v5
+        with:
+          go-version: stable
+          cache-dependency-path: go.sum
+
+      - name: start shell
+        run: |
+          cat >start.sh<<EOF
+          ulimit -n 65535 && TAOS_SUPPORT_VNODES=256 taosd
+          EOF
+
+      - name: start taosd
+        run: nohup sudo sh ./start.sh & disown
+
+      - name: build taosAdapter
+        run: go build -cover
+
+      - name: run test
+        run: |
+          sudo chmod +x ./tests/e2e.sh || true
+          sudo bash ./tests/e2e.sh
+
+      - name: merge coverage
+        run: |
+          sudo go tool covdata textfmt -i=coverage -o=cov.txt
+
+      - name: Upload coverage to Codecov
+        if: matrix.os == 'ubuntu-latest'
+        uses: codecov/codecov-action@v5
+        with:
+          files: ./cov.txt
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
+          OS: linux
